moderation:
  logs-channel: "1388256659154927717"
  warns:
    embed:
      color: "#F58027"
      title: "User warned"
    user-embed:
      color: "#F58027"
      title: "You got warned!"
      description: "You got a warn for the reason: ```{reason}```"