moderation:
  logs-channel: "1388256659154927717"
  warns:
    embed:
      color: "#F58027"
      title: "User warned"
    user-embed:
      color: "#F58027"
      title: "You got warned!"
      description: "You got a warn for the reason: ```{reason}```"
  warnlist:
      embed:
        color: "#F58027"
        title: "User warn"
        fields-title:
          reason: "Reason"
          moderator: "Moderator"
          date: "Date"
      buttons:
        prev: "Previous"
        next: "Next"
      cant-use-buttons: "You can't use these buttons"
  mute:
    embed:
      color: "#F58027"
      title: "User muted"
    user-embed:
      color: "#F58027"
      title: "You got muted!"
      description: "You got a mute for the reason: ```{reason}```"
  ban:
    embed:
      color: "#F58027"
      title: "User muted"
    user-embed:
      color: "#F58027"
      title: "You got muted!"
      description: "You got a mute for the reason: ```{reason}```"