leveling:

  disallowed-channels:
    - 123456789123456
    - 000000000000000

  broadcast-level-up: true

  levelup-broadcast-channel: reply # or a custom channel ID

  broadcast-level-up-embed:
    title: "You got a new level!"
    description: "Congrats {user.mention}! You achieved a new level ({level})! Keep chatting to get new levels"
    color: '#00e269'
    footer:
      text: "Level Up!"
      icon_url: "{user.avatar_url}"
    thumbnail:
      url: "{user.avatar_url}"

  xp-threshold: 2000 # Formula: required-xp = user-level * xp-threshold
  min-xp: 1
  max-xp: 10

  rank-command-embed:
    title: "{user}'s rank"
    fields-title:
      level: "Level"
      xp: "XP"
      progress: "Progress"
    request: "Requested by {requester}"
    color: "#00e269"
  
  top-command-embed:
    title: "🏆 Top 10 users"
    fields-title:
      level: "Level"
      xp: "XP"
    request: "Requested by {requester}"
    color: "#00e269"
